name: "Validate devcontainer-feature.json files"
on:
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          validate-only: "true"
          base-path-to-features: "./src"
